### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by d4v3y0rk**
updated the readme with some info

### CODE REVIEW

**Comment by razzeee** [comment]
I'm having problems getting this to work. I think I needed to skip install of "apt-utils" as it wasn't available?

Also can you make up an example for `<WEB_URL_TO_LOGIN>` as I'm not sure if it fails due to me handing it the wrong format.

Another question, will this only tunnel firefox? I need more to go via netscaler, vscode or ssh come to mind.

**Comment by d4v3y0rk** [comment]
> I'm having problems getting this to work. I think I needed to skip install of "apt-utils" as it wasn't available?

I looked and it seems the apt-utils is still available for ubuntu 18.04 i386 arch. Are you running commands provided in the readme?

 
> Also can you make up an example for `<WEB_URL_TO_LOGIN>` as I'm not sure if it fails due to me handing it the wrong format.

The url is simply https://connect.to.your.server.com
 
> Another question, will this only tunnel firefox? I need more to go via netscaler, vscode or ssh come to mind.

This is not for using the netscaler VPN tunnel. The Netscaler plugin as far as I know is only for use with the browser and it is triggered by the browser handler in order to make sure your machine meets whatever criteria your Netscaler Administrator has designated.

**Comment by d4v3y0rk** [comment]
Here is a link to the package which seems to be available for multiple architectures. 
https://ubuntu.pkgs.org/18.04/ubuntu-main-i386/apt-utils_1.6.1_i386.deb.html

**Comment by d4v3y0rk** [comment]
I have a bash script for launching the connection to the running docker container instance:

```
#!/bin/bash
ssh -f -X receiver@$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' citrix) -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /usr/bin/firefox https://my.server.org/epa/epa.html  > /dev/null 2>&1
```

**Comment by d4v3y0rk** [comment]
I just ran the build again locally. It seems to be building properly. I am going to try it on a different system and see how it goes @Razzeee

**Comment by razzeee** [comment]
Is this supposed to happen?

```
Step 7/14 : RUN dpkg -i /tmp/nsginstaller64.deb &&     rm /tmp/nsginstaller64.deb
 ---> Running in a38aa9f5daee
Selecting previously unselected package nsgclient.
(Reading database ... 32600 files and directories currently installed.)
Preparing to unpack /tmp/nsginstaller64.deb ...
/var/lib/dpkg/tmp.ci/preinst: line 5: killall: command not found
/var/lib/dpkg/tmp.ci/preinst: line 6: sudo: command not found
Unpacking nsgclient (0.0.0.1) ...
Setting up nsgclient (0.0.0.1) ...
/var/lib/dpkg/info/nsgclient.postinst: line 39: update-desktop-database: command not found
nsgverctl: unrecognized service
```

**Comment by d4v3y0rk** [comment]
@Razzeee That is not the same package that I am installing in my dockerfile for the netscaler gateway. The package I am installing is the browser plugin: nsepa.deb

**Comment by razzeee** [comment]
Sorry, I'm getting the same messages with both Deb files. Do I just need to login in Firefox after executing the script, or do I need to do something after the login.

That does mean, that this will only help being able to access websites, and not ssh?

**Pull request merged**
